### ISSUE TITLE
Total playback time is abnormally long when running in Safari / Safariで処理すると総再生時間が変

### ISSUE THREAD

**Issue by tamaina** [tamaina/venc2#1]
However Chrome-processed videos don't increase total playback time.

![image](https://github.com/tamaina/venc2/assets/7973572/863796bb-a9b5-400b-afc0-6c1d01802a49)

![image](https://github.com/tamaina/venc2/assets/7973572/bebaecf8-a80b-4b9b-905b-73755ad75dc7)

**Comment by tamaina** [comment]
https://github.com/tamaina/venc2/assets/7973572/508fbf5f-a510-4d98-9256-6cf1506f89e4

Safariで作ったmp4

**Comment by tamaina** [comment]
ffmpegはmfra/tfra boxをつけているので、mfra/tfra boxを追加すればうまいこといきそうではあるがmp4boxを改造する必要がある

![image](https://github.com/tamaina/venc2/assets/7973572/a5920828-6913-42b5-9a05-e011bda65dca)

**Comment by tamaina** [comment]
とりあえずIssueを出してみた https://github.com/gpac/mp4box.js/issues/355

**Comment by tamaina** [comment]
でも[workerではない処理系](https://github.com/tamaina/venc2/releases/tag/0.0.0-notworker)の時は普通に時間合ってたんだよな

**Comment by tamaina** [comment]
> でも[workerではない処理系](https://github.com/tamaina/venc2/releases/tag/0.0.0-notworker)の時は普通に時間合ってたんだよな

でもなんか異常なので今の実装の方が正しいのかも

**Comment by tamaina** [comment]
（ところで: Chromeで処理した動画が2倍で済んでてSafariで処理した動画はめっちゃ長い理由を理解していない）

**Comment by tamaina** [comment]
MEMO: https://github.com/Dash-Industry-Forum/codem-isoboxer/blob/master/src/processors/tfra.js

**Comment by tamaina** [comment]
[mfra/tfra/mfroを書いてみた](https://github.com/tamaina/venc2/blob/579d50fe53e6cc1880ac467a6c69fa3d13d089b6/src/index.ts#L281-L318)けど解決しなかった

**Comment by tamaina** [comment]
![image](https://github.com/tamaina/venc2/assets/7973572/f0947861-bec9-4bd9-9272-33f584cb0b75)

ffmpeg/ffprobeも同じような時間を出してくる

**Comment by tamaina** [comment]
ffmpegのソースを読めば原因が分かりそうだけどパッと検索した限り端緒を見つけられなかった

**Comment by tamaina** [comment]
https://github.com/FFmpeg/FFmpeg/blob/fa20f5cd9e131f22da06ef57bf5aedd87ff51a90/libavformat/dump.c#L644-L669

ここら辺かしら

**Comment by tamaina** [comment]
durationの触り始め

https://github.com/FFmpeg/FFmpeg/blob/master/libavformat/demux.c#L295

**Comment by tamaina** [comment]
ここ

https://github.com/FFmpeg/FFmpeg/blob/fa20f5cd9e131f22da06ef57bf5aedd87ff51a90/libavformat/demux.c#L1660

**Comment by tamaina** [comment]
こっちかも

https://github.com/FFmpeg/FFmpeg/blob/fa20f5cd9e131f22da06ef57bf5aedd87ff51a90/libavformat/demux.c#L1560  
https://github.com/FFmpeg/FFmpeg/blob/fa20f5cd9e131f22da06ef57bf5aedd87ff51a90/libavformat/demux.c#L1671

**Comment by tamaina** [comment]
https://github.com/FFmpeg/FFmpeg/blob/fa20f5cd9e131f22da06ef57bf5aedd87ff51a90/libavformat/demux.c#L1619

av_rescale_qが変なんかな

**Comment by tamaina** [comment]
`r_frame_rate`がおかしくて、これによって色々ダメなことが起きてるらしい

**Comment by tamaina** [comment]
ログによれば max_analyze_duration に引っかかってるっぽい

https://github.com/FFmpeg/FFmpeg/blob/fa20f5cd9e131f22da06ef57bf5aedd87ff51a90/libavformat/demux.c#L2730

**Comment by tamaina** [comment]
いや結局それってtime_baseがおかしいので(？)ffmpegの内部durationが滅茶苦茶になっているだけだよな

**Comment by tamaina** [comment]
VideoEncoderで指定してやらないとdescriptionのSPSのフレームレートが変になって、そいでもってtime_baseがおかしくなるのか

**Comment by tamaina** [comment]
残念ながらVideoEncoderにframerateを設定しても変わらん

**Comment by tamaina** [comment]
avcDecoderConfigRecord Safari vs Chrome

![image](https://github.com/tamaina/venc2/assets/7973572/dd3080f2-b112-4e74-b160-90d9232e31e0)

**Comment by tamaina** [comment]
（最後のPPSが変わってないからいいじゃんと思ったけど関係あるのは真ん中のSPSだったわ）

**Comment by tamaina** [comment]
SPSのパース

https://github.com/FFmpeg/FFmpeg/blob/fa20f5cd9e131f22da06ef57bf5aedd87ff51a90/libavcodec/h264_ps.c#L142-L158

timing_info_present_flagがあったらここでframerateとして記録している？

https://github.com/FFmpeg/FFmpeg/blob/fa20f5cd9e131f22da06ef57bf5aedd87ff51a90/libavcodec/h264_parser.c#L570-L571

**Comment by tamaina** [comment]
> timing_info_present_flagがあったらここでframerateとして記録している？

av_reduceは引数2, 3を約分して引数0, 1に記録するという感じらしい

**Comment by tamaina** [comment]
https://wikiwiki.jp/redstrange/H.264

**Comment by tamaina** [comment]
https://github.com/FFmpeg/FFmpeg/blob/fa20f5cd9e131f22da06ef57bf5aedd87ff51a90/libavcodec/h264_ps.c#L560

**Comment by tamaina** [comment]
> https://github.com/FFmpeg/FFmpeg/blob/fa20f5cd9e131f22da06ef57bf5aedd87ff51a90/libavcodec/h264_ps.c#L560

これの起動の仕方に15分悩んでたけどコマンドに`-debug pict`を付け足せばいけた

**Comment by tamaina** [comment]
memo

```bash
ffprobe target.mp4  -hide_banner -loglevel warning -loglevel info -loglevel verbose -loglevel debug -debug pict -of default -show_streams
```

![image](https://github.com/tamaina/venc2/assets/7973572/69c19ebf-23cf-451b-a530-ef338087db43)

**Comment by tamaina** [comment]
r_frame_rateは主に[ff_rfps_calculate](https://github.com/FFmpeg/FFmpeg/blob/63eb630915b9ef92d21e521d610ed9d3ee2f358f/libavformat/demux.c#L2266)が決定してそうだけど解読が億劫

**Comment by tamaina** [comment]
睡眠を経て開いたら何をやってたかわからなくなったが結局SPSをいじってnum_units_in_tick/time_scaleを突っ込むのが手っ取り早い気がしていたのは覚えている

**Comment by tamaina** [comment]
ChatGPTに聞いてみた

そんなコマンドあるんだ

![image](https://github.com/tamaina/venc2/assets/7973572/a50f494a-93dd-4783-82f2-364a44861d49)

**Comment by tamaina** [comment]
SPSをいじらなくてもVideoEncoderのconfig.decoderConfig.descriptionがtiming_info_present_flag=1にしてくれれば済む件

**Comment by tamaina** [comment]
つかedts/elstのmedia_timeを参考にしてくれれば悩むことないんだけどそういうふうに仕向けられないかしら

**Comment by Mr-Ojii** [comment]
少し調べてみたところ、こちらの問題はtransform.tsで最終フレーム付近のフレームのソートが正常にできていないのが問題のようです

**Comment by tamaina** [comment]
エンコードした後のtimestampが順番通りでなく出てきてるんだわこれ

**Comment by tamaina** [comment]
EncodedVideoChunkはソートしてはいけないのでうーん

**Comment by tamaina** [comment]
durationをsortの時点で付与するかしら
